function(pyraqt_find_qt)
    set(_qt_components Core Gui Widgets LinguistTools Test)

    if(PYRAQT_QT_MAJOR_VERSION STREQUAL "6")
        list(APPEND _qt_components OpenGLWidgets)
        find_package(Qt6 6.5 REQUIRED COMPONENTS ${_qt_components})
        set(PYRAQT_QT_PACKAGE Qt6 PARENT_SCOPE)
        set(PYRAQT_QT_VERSION_MAJOR 6 PARENT_SCOPE)
    elseif(PYRAQT_QT_MAJOR_VERSION STREQUAL "5")
        list(APPEND _qt_components OpenGL)
        find_package(Qt5 5.15 REQUIRED COMPONENTS ${_qt_components})
        set(PYRAQT_QT_PACKAGE Qt5 PARENT_SCOPE)
        set(PYRAQT_QT_VERSION_MAJOR 5 PARENT_SCOPE)
    else()
        set(_qt6_components ${_qt_components})
        list(APPEND _qt6_components OpenGLWidgets)
        find_package(Qt6 6.5 QUIET COMPONENTS ${_qt6_components})
        if(Qt6_FOUND)
            set(PYRAQT_QT_PACKAGE Qt6 PARENT_SCOPE)
            set(PYRAQT_QT_VERSION_MAJOR 6 PARENT_SCOPE)
        else()
            list(APPEND _qt_components OpenGL)
            find_package(Qt5 5.15 REQUIRED COMPONENTS ${_qt_components})
            set(PYRAQT_QT_PACKAGE Qt5 PARENT_SCOPE)
            set(PYRAQT_QT_VERSION_MAJOR 5 PARENT_SCOPE)
        endif()
    endif()

    if(Qt6_FOUND)
        add_library(PyraQt::QtCore ALIAS Qt6::Core)
        add_library(PyraQt::QtGui ALIAS Qt6::Gui)
        add_library(PyraQt::QtWidgets ALIAS Qt6::Widgets)
        add_library(PyraQt::QtTest ALIAS Qt6::Test)
        add_library(PyraQt::QtOpenGLWidgets ALIAS Qt6::OpenGLWidgets)
    else()
        add_library(PyraQt::QtCore ALIAS Qt5::Core)
        add_library(PyraQt::QtGui ALIAS Qt5::Gui)
        add_library(PyraQt::QtWidgets ALIAS Qt5::Widgets)
        add_library(PyraQt::QtTest ALIAS Qt5::Test)
        add_library(PyraQt::QtOpenGLWidgets ALIAS Qt5::OpenGL)
    endif()
endfunction()

function(pyraqt_add_resources out_var)
    set(${out_var} ${ARGN} PARENT_SCOPE)
endfunction()

function(pyraqt_add_translations out_var)
    if(Qt6_FOUND AND TARGET Qt6::lrelease)
        get_target_property(_lrelease_location Qt6::lrelease IMPORTED_LOCATION)
    elseif(DEFINED Qt5_LRELEASE_EXECUTABLE)
        set(_lrelease_location "${Qt5_LRELEASE_EXECUTABLE}")
    else()
        find_program(_lrelease_location lrelease REQUIRED)
    endif()

    set(_translations)
    foreach(_ts_file IN LISTS ARGN)
        get_filename_component(_ts_abs "${_ts_file}" ABSOLUTE BASE_DIR "${CMAKE_CURRENT_SOURCE_DIR}")
        get_filename_component(_translation_name "${_ts_abs}" NAME_WE)
        set(_qm_file "${CMAKE_CURRENT_BINARY_DIR}/${_translation_name}.qm")
        add_custom_command(
            OUTPUT "${_qm_file}"
            COMMAND "${_lrelease_location}" "${_ts_abs}" -qm "${_qm_file}"
            DEPENDS "${_ts_abs}"
            VERBATIM
        )
        list(APPEND _translations "${_qm_file}")
    endforeach()

    set(${out_var} ${_translations} PARENT_SCOPE)
endfunction()
